      app: index
  template:
    metadata:
      labels:
        app: index
    spec:
      containers:
      - name: index-container
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html-volume
        configMap:
          name: html-configmap
          items:
          - key: index.html
            path: index.html
